input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  # Garante que traceId e spanId sejam campos de primeiro nível para facilitar busca no Kibana
  if [traceId] {
    mutate {
      add_field => { "correlation_id" => "%{traceId}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
}
