server:
  port: 8081

spring:
  application:
    name: music-service

  datasource:
    url: jdbc:mysql://localhost:3307/music_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate          # nunca alterar schema em produção — o init.sql faz isso
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
